# Generated by Django 4.2.13 on 2024-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0004_contactos_foto_alter_usuarios_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='foto',
        ),
    ]
