# Generated by Django 4.2.13 on 2024-06-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0005_remove_contactos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='email',
        ),
    ]
