# Generated by Django 4.2.13 on 2024-06-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0006_remove_contactos_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
