# Generated by Django 4.2.13 on 2024-06-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0008_persona_usuario_alter_contactos_usuarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='usuarios',
            new_name='persona',
        ),
    ]
