# Generated by Django 4.2.13 on 2024-06-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0011_rename_usuario_user_persona_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactos',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='usuario',
            new_name='user',
        ),
    ]
