# Generated by Django 4.2.13 on 2024-06-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0012_rename_usuario_contactos_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AgendaContactosApp.user'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='AgendaContactosApp.user'),
        ),
    ]
