# Generated by Django 4.2.13 on 2024-06-09 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0013_alter_contactos_user_alter_persona_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='imagenes/foto_usuario/default.png', upload_to='foto_usuario'),
        ),
    ]
