# Generated by Django 4.2.13 on 2024-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaContactosApp', '0014_alter_persona_fecha_nacimiento_alter_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='foto',
            field=models.ImageField(default='foto_usuario/default.png', upload_to='foto_contacto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='foto_usuario/default.png', upload_to='foto_usuario'),
        ),
    ]
